development:
  S3_BUCKET_NAME: splickitykidsdev
  ACCESS_KEY_ID: AKIAIPIONVAD2O24H6RA
  SECRET_ACCESS_KEY: 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
  STRIPE_API_KEY: sk_test_WatLZezBFQofjB0YSnWNu0Wz
  STRIPE_PUBLISHABLE_KEY: pk_test_9aUARyBvfl5WmI5tnCQBa2GH
test:
  S3_BUCKET_NAME: splickitykidsdev
  ACCESS_KEY_ID: AKIAIPIONVAD2O24H6RA
  SECRET_ACCESS_KEY: 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
  STRIPE_API_KEY: sk_test_uN2PgAGJE3l4NpiogZ3mzVmY
  STRIPE_PUBLISHABLE_KEY: pk_test_3sDlEq9iyFC99RxlHSqp3rpG

production:
  S3_BUCKET_NAME: splickitykids
  ACCESS_KEY_ID: AKIAIPIONVAD2O24H6RA
  SECRET_ACCESS_KEY: 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
  STRIPE_API_KEY: sk_live_eXsq318CEKssvJ40YODgsf24
  STRIPE_PUBLISHABLE_KEY: pk_live_0G3ENqSpfOoBlcjo2JDVDlbN
