STRIPE_API_KEY: sk_test_CMp4q5GI2GTSHN3WHPEuMjsk
STRIPE_PUBLISHABLE_KEY: pk_test_jlAjdQPShhVVH5kTrY6Z278t
STRIPE_CLIENT_ID: ca_9hmQykKoRyn8ROY9VqFaahvT8WfYqbkQ
RECAPTCHA_PUBLIC_KEY: "6LdmNQ4UAAAAAIztZ9Mn3i9yQ_fablO0MRWeRn6M"
RECAPTCHA_SECRET_KEY: "6LdmNQ4UAAAAAFL96b81aKs2AYxZzZdacKHRYjdY"
