development:
  bucket: splickitykids
  access_key_id: ENV["ACCESS_KEY_ID"]
  secret_access_key: ENV["SECRET_ACCESS_KEY"]
test:
  bucket: splickitykids
  access_key_id: ENV["ACCESS_KEY_ID"]
  secret_access_key: ENV["SECRET_ACCESS_KEY"]
production:
  bucket: splickitykids
  access_key_id: ENV["ACCESS_KEY_ID"]
  secret_access_key: ENV["SECRET_ACCESS_KEY"]