development:
  bucket: <%= ENV["S3_BUCKET_NAME"] %>
  access_key_id: <%= ENV["ACCESS_KEY_ID"] %>
  secret_access_key: <%= ENV["SECRET_ACCESS_KEY"] %>
test:
  bucket: <%= ENV["S3_BUCKET_NAME"] %>
  access_key_id: <%= ENV["ACCESS_KEY_ID"] %>
  secret_access_key: <%= ENV["SECRET_ACCESS_KEY"] %>
production:
  bucket: <%= ENV["S3_BUCKET_NAME"] %>
  access_key_id: <%= ENV["ACCESS_KEY_ID"] %>
  secret_access_key: <%= ENV["SECRET_ACCESS_KEY"] %>